/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f0xx.h"
void delay(void){
	for(uint32_t i=0;i<500000;i++);
}



int main(void)
{
GPIO_Handle_t GpioLed;
//GPIOC_PCLK_EN();     //enable clk for port c

//GpioLed.GPIO_PinConfig->GPIO_PinNumber= GPIO_PIN_NO_8;

GpioLed.pGPIOx= GPIOC;

GPIO_PeriClockControl(GPIOC, ENABLE);

//clock sahi chal raha hai


GpioLed.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_8;
GpioLed.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUT;
GpioLed.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_HIGH;
GpioLed.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_NO_PUPD;

GPIO_Init(&GpioLed);





//clock sahi chal raha hai



while(1){

			delay(); //providing this delay to avoid debouncing
			GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_NO_8);

}
//	GPIOC_PCLK_EN();     //enable clk for port c

//	GPIO_RegDef_t mygpio;
//	mygpio =GPIOC;
//	mygpio->MODER |=(1<<16);//enable port c pin 8 as a digital output.
//	GPIOC->ODR |=(1<<8); //turn GPIOC pin 8 on or assert high

/* Loop forever */
return 0;
}
