/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f0xx.h"
void delay(void){
	for(uint32_t i=0;i<500000;i++);
}



int main(void)
{
GPIO_Handle_t GpioLed,GpioLed1;
//GPIOC_PCLK_EN();     //enable clk for port c

//GpioLed.GPIO_PinConfig->GPIO_PinNumber= GPIO_PIN_NO_8;

GpioLed.pGPIOx= GPIOC;
GpioLed1.pGPIOx= GPIOA;
GPIO_PeriClockControl(GPIOC, ENABLE);
GPIO_PeriClockControl(GPIOA, ENABLE);
//clock sahi chal raha hai


GpioLed.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_8;
GpioLed.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUT;
GpioLed.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_HIGH;
GpioLed.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_NO_PUPD;

GPIO_Init(&GpioLed);




//clock sahi chal raha hai


GpioLed1.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_0;
GpioLed1.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_IN;
GpioLed1.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_HIGH;
//GpioLed1.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
GpioLed1.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_NO_PUPD; //no pullup pull down state me A0 will have 1 state on pressing.

GPIO_Init(&GpioLed1);

while(1){
	if(GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0))
		{
			delay(); //providing this delay to avoid debouncing
			GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_NO_8);
		}

}

/* Loop forever */
return 0;
}
